### ISSUE TITLE
How to encode Video file using encoder

### ISSUE THREAD

**Issue by mushahidh** [catid/longhair#3]
I have encoded H.264 bit stream. Before streaming the video using RTP i want to encode the video using longhair. But i could not understand how to give video as an input to encoder so that it can recover packet loss during transmission at receiver end.
Any help would be highly appreciated.

**Comment by catid** [comment]
Sorry I don't think that's in scope of this project, which is just a low-level math library.  I would expect you'd need a higher-level library for that to integrate with your stack.
