### ISSUE TITLE
erroneous/random byte error support?

### ISSUE THREAD

**Issue by my12doom** [catid/longhair#4]
we are trying to stream video from a drone, which has a datalink that have both packet losses and random byte errors(~0.05%). currently we are using classic reed solomon implementation and it works fine except for heavy computation load on  embedded computers.

it appears longhair library doesn't support correcting random byte error even provided with additional packets?

**Comment by oculuscat** [comment]
Hey glad it's useful for you!  I have a new library (based on some new types of FEC!) for exactly that use case but it's not ready for release yet.

I would add a checksum or hash to each packet and use that to detect the random byte errors.

Note that checksums can also be used to correct one bit errors in small data packets:
https://github.com/catid/CRC16Recovery

**Comment by catid** [comment]
In terms of speeding up Reed-Solomon this is pretty good:

https://github.com/catid/Fast-algorithms-of-Reed-Solomon-erasure-codes

I found that the encoder was very fast but the decoder was 5x slower than the encoder.  So if your encoder is on the drone then it should be suitable.  The only problem may be that it doesn't seem very easy to use.

**Comment by catid** [comment]
Yes: The library doesn't support that.
