### ISSUE TITLE
Some performance questions

### ISSUE THREAD

**Issue by jorangreef** [catid/longhair#7]
Thanks @catid for some awesome code.

I implemented https://github.com/ronomon/reed-solomon based on Backblaze's module. This was one of my first C projects. I would like to write a Cauchy Reed Solomon open source implementation for better performance and also for personal learning/understanding. Would you be willing to help me out on some questions?

I have been going through longhair and CM256 to try and understand the performance differences.

> It is extremely fast, though not as fast as the CM256 library.

What all goes into making CM256 faster? Sorry if I missed it in the docs or code.

Should people always use CM256 or is there a use-case for longhair? Is CM256 limited in some way?

Would you be able to go into more detail on why longhair/CM256 is faster than jerasure?

Before settling on CRS, I was thinking of liber8tion and was also wondering if you had experience with that?

Your advice would be much appreciated.

**Comment by catid** [comment]
On desktop PCs the number of memory accesses is roughly equal to the execution time.  CM256 uses fewer memory accesses and heavier math operations.  Longhair does more (approx Log8=3) memory accesses and lighter math (xor).  On embedded targets without the heavy ops that CM256 uses, Longhair wins.  On desktops, CM256 wins

**Comment by catid** [comment]
You might also look at the Leopard project which is a more complex but faster version of CM255 that also supports far more symbols (65536)

**Comment by jorangreef** [comment]
Thanks @catid.
